
MOLD_PATTERNS = {
    "tfc:ceramic/ingot_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/hammer_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXX  XXXXXXX",
        "XXXX    XXXXXX",
        "XXX      XXXXX",
        "XX        XXXX",
        "XX         XXX",
        "XXX         XX",
        "XXXX        XX",
        "XXXXX      XXX",
        "XXXXXX    XXXX",
        "XXXXXXX  XXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfcchannelcasting:heart_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXX  XX  XXXX",
        "XXX        XXX",
        "XX          XX",
        "XX          XX",
        "XX          XX",
        "XXX        XXX",
        "XXXX      XXXX",
        "XXXXX    XXXXX",
        "XXXXXX  XXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/hoe_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XX       XXXXX",
        "XXX       XXXX",
        "XXXXXX     XXX",
        "XXXXXXXX    XX",
        "XXXXXXXXX   XX",
        "XXXXXXXXXX  XX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/javelin_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XX  XXXXXXXXXX",
        "XX    XXXXXXXX",
        "XXX     XXXXXX",
        "XXX      XXXXX",
        "XXXX      XXXX",
        "XXXX       XXX",
        "XXXXX      XXX",
        "XXXXXX     XXX",
        "XXXXXXX     XX",
        "XXXXXXXXXX  XX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/knife_blade_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XX  XXXXXXXXXX",
        "XX   XXXXXXXXX",
        "XX    XXXXXXXX",
        "XX     XXXXXXX",
        "XXX     XXXXXX",
        "XXXX     XXXXX",
        "XXXXX     XXXX",
        "XXXXXX     XXX",
        "XXXXXXXXX   XX",
        "XXXXXXXXXX  XX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/axe_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXX  XXXXXX",
        "XXXXX    XXXXX",
        "XXXX     XXXXX",
        "XXX      XXXXX",
        "XX        XXXX",
        "XX         XXX",
        "XXX         XX",
        "XXXXXX      XX",
        "XXXXXXX     XX",
        "XXXXXXXX   XXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/chisel_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXX XXXXXXXXX",
        "XXX   XXXXXXXX",
        "XX     XXXXXXX",
        "XXX     XXXXXX",
        "XXXX     XXXXX",
        "XXXXX     XXXX",
        "XXXXXX     XXX",
        "XXXXXXX     XX",
        "XXXXXXXX    XX",
        "XXXXXXXXX  XXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/mace_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXX  XXXX",
        "XXXXXX     XXX",
        "XXXXXX      XX",
        "XXXX        XX",
        "XXXX       XXX",
        "XXX        XXX",
        "XXX      XXXXX",
        "XXX      XXXXX",
        "XXXX   XXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/propick_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XX     XXXXXXX",
        "XXX     XXXXXX",
        "XXXX     XXXXX",
        "XXXXX     XXXX",
        "XXXXXX     XXX",
        "XXXXXXX     XX",
        "XXXXXXXX    XX",
        "XXXXXXXXX  XXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/pickaxe_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XX      XXXXXX",
        "XXX       XXXX",
        "XXXX       XXX",
        "XXXXXXX    XXX",
        "XXXXXXXX    XX",
        "XXXXXXXXX   XX",
        "XXXXXXXXX   XX",
        "XXXXXXXXX   XX",
        "XXXXXXXXXX  XX",
        "XXXXXXXXXXX XX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/saw_blade_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXX  XXXXXXXXX",
        "XX     XXXXXXX",
        "XX       XXXXX",
        "XX        XXXX",
        "XXXX        XX",
        "XXXX        XX",
        "XXXXXX      XX",
        "XXXXXX      XX",
        "XXXXXXXX    XX",
        "XXXXXXXX   XXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/scythe_blade_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXX      XXXX",
        "XX         XXX",
        "XXXXXX      XX",
        "XXXXXXXX    XX",
        "XXXXXXXXX  XXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/shovel_head_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXX    XXXX",
        "XXXXX      XXX",
        "XXXX       XXX",
        "XXX        XXX",
        "XXX        XXX",
        "XXXX      XXXX",
        "XXXXX    XXXXX",
        "XXXXXX  XXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/sword_blade_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXX   XX",
        "XXXXXXXX    XX",
        "XXXXXXX     XX",
        "XXXXXX     XXX",
        "XXXXX     XXXX",
        "XXXX     XXXXX",
        "XXX     XXXXXX",
        "XX     XXXXXXX",
        "XX    XXXXXXXX",
        "XXX  XXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
    "tfc:ceramic/bell_mold": [
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
        "XXXXXX  XXXXXX",
        "XXXXX    XXXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXXX      XXXX",
        "XXX        XXX",
        "XX          XX",
        "XX          XX",
        "XXXXXXXXXXXXXX",
        "XXXXXXXXXXXXXX",
    ],
}

MOLD_PATTERNS["tfc:ceramic/fire_ingot_mold"] = MOLD_PATTERNS["tfc:ceramic/ingot_mold"]